testing upload assests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,84 +34,74 @@ jobs:
           if [ -z "$TAG" ]; then TAG=0; fi
           echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
 
-      # - name: Build modules/APKs
-      #   run: ./build.sh config.toml
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     GITHUB_REPOSITORY: $GITHUB_REPOSITORY
-      #     NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
-      #
-      # - name: Get output
-      #   id: get_output
-      #   run: |
-      #     DELIM="$(openssl rand -hex 8)"
-      #     echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
-      #     cat build.md >> "$GITHUB_OUTPUT"
-      #     echo "${DELIM}" >> "$GITHUB_OUTPUT"
-      #     cp -f build.md build.tmp
-      #
-      #     
-      # - name: Upload modules to release
-      #   uses: svenstaro/upload-release-action@v2
-      #   with:
-      #     body: ${{ steps.get_output.outputs.BUILD_LOG }}
-      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
-      #     file: ./build/*
-      #     release_name: ReVancedEx
-      #     tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
-      #     file_glob: true
-      #     overwrite: true
-      #
-      # - name: Upload Assets 
-      #   uses: svenstaro/upload-release-action@v2
-      #   with:
-      #     file: assets/*
-      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
-      #     body: "This is my assets upload TExt"
-      #     asset_name: "ReX Config.json"
-      #     tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
-      #     # file_glob: true
-      #     overwrite: true
-      #     
-      # - name: Update changelog and Magisk update json
-      #   id: update_config
-      #   run: |
-      #     git checkout -f update || git switch --discard-changes --orphan update
-      #     cp -f build.tmp build.md
-      #     get_update_json() {
-      #       echo "{
-      #       \"version\": \"$1\",
-      #       \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
-      #       \"zipUrl\": \"$2\",
-      #       \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
-      #     }"
-      #     }
-      #
-      #     cd build || { echo "build folder not found"; exit 1; }
-      #     for OUTPUT in *magisk*.zip; do
-      #       [ "$OUTPUT" = "*magisk*.zip" ] && continue
-      #       ZIP_S=$(unzip -p "$OUTPUT" module.prop)
-      #       if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
-      #       UPDATE_JSON="${UPDATE_JSON##*/}"
-      #       VER=$(echo "$ZIP_S" | grep version=)
-      #       VER="${VER##*=}"
-      #       DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
-      #       get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
-      #     done
-      #     cd ..
-      #
-      #     find . -name "*-update.json" | grep . || : >dummy-update.json
+      - name: Build modules/APKs
+        run: ./build.sh config.toml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
+          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+      - name: Get output
+        id: get_output
+        run: |
+          DELIM="$(openssl rand -hex 8)"
+          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+          cat build.md >> "$GITHUB_OUTPUT"
+          echo "${DELIM}" >> "$GITHUB_OUTPUT"
+          cp -f build.md build.tmp
+
+          
+      - name: Upload modules to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          body: ${{ steps.get_output.outputs.BUILD_LOG }}
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: ./build/*
+          release_name: ReVancedEx
+          tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+          file_glob: true
+          overwrite: true
 
       - name: Upload Assets 
         uses: svenstaro/upload-release-action@v2
         with:
-          file: "./assets/dd.json"
+          file: "./assets/*.json"
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           body: "This is my assets upload TExt"
           asset_name: "ReX Config.json"
           tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
           # file_glob: true
           overwrite: true
+          
+      - name: Update changelog and Magisk update json
+        id: update_config
+        run: |
+          git checkout -f update || git switch --discard-changes --orphan update
+          cp -f build.tmp build.md
+          get_update_json() {
+            echo "{
+            \"version\": \"$1\",
+            \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+            \"zipUrl\": \"$2\",
+            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
+          }"
+          }
+
+          cd build || { echo "build folder not found"; exit 1; }
+          for OUTPUT in *magisk*.zip; do
+            [ "$OUTPUT" = "*magisk*.zip" ] && continue
+            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+            UPDATE_JSON="${UPDATE_JSON##*/}"
+            VER=$(echo "$ZIP_S" | grep version=)
+            VER="${VER##*=}"
+            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+          done
+          cd ..
+
+          find . -name "*-update.json" | grep . || : >dummy-update.json
+
             
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
